### ISSUE TITLE
Been unable to check my feed

### ISSUE THREAD

**Issue by arkindal** [TeamPiped/Piped#1195]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

My feed list is permanently empty.

I tried re importing my subscriptions, I tried checking from different devices and I tried using a connection different from my own. Sometimes I can’t even login. 

At first I assumed it was an issue with my pc but it clearly isn’t. Should this help, I’m from Italy.

My subscription list went empty on top of all that, so I tried subscribing to something random and after checking my subscription list I saw that it was still empty to my surprise. At that point I assumed the issue was related to my account, that’s when I made a new one but all those issues are still there.

### To Reproduce

login
Check subscriptions or feed
???
Opposite of profit

### Expected behavior

I should be able to see my subscription

### Logs/Errors

Not available

### Browser, and OS with Version.

This was tested on different devices and browsers:
Endeavour linux: librewolf, firefox
Microsoft windows: google chrome
Ios: Safari
Android: mull

**Comment by Tha14** [comment]
Same problem and this is on the official instance. I also noticed that in preferences the instance does not appear anymore:
![image](https://user-images.githubusercontent.com/5931740/178152532-1a5bf0c6-e0e1-47b6-b86c-9144bb70126d.png)

**Comment by arkindal** [comment]
Oh yeah, now that @Tha14 brings instances up, I forgot to mention that I also tried using another instance. Same issue.

**Comment by hommegithub** [comment]
Hell yeah! I thought I'm the only one and it comes down to account level!!!!!!

**Comment by arkindal** [comment]
I prefer piped by far but for now I'm using invidious too like hommegithub did, but personally I don't think I have experienced the same errors. There have been times where I couldn't reach the page but the problem sorted itself out quickly so I didn't really give it much importance.

**Comment by Abystus** [comment]
At this point this issue has been going on for a week or more with no responses or fixes. Have the developers given up on this project?

**Comment by Pentaphon** [comment]
> At this point this issue has been going on for a week or more with no responses or fixes. Have the developers given up on this project?

I think it's time for all the devs to come together and merge their efforts with the Invidious project. There's no need to have 2 or more different kinds of privacy-friendly Youtube frontends. We just need 1 project that everybody can focus on.

**Comment by Pentaphon** [comment]
> For example, does this video work for you? https://invidious.tiekoetter.com/watch?v=XL1iuROr8W4

On other instances it does. I've never used that instance. 

I'd rather have both projects be fully merged together so we get the best of both worlds no matter what. It's not like they look or behave much differently anyway.

**Comment by arkindal** [comment]
> > For example, does this video work for you? https://invidious.tiekoetter.com/watch?v=XL1iuROr8W4
> 
> On other instances it does. I've never used that instance.
> 
> I'd rather have both projects be fully merged together so we get the best of both worlds no matter what. It's not like they look or behave much differently anyway.

Could you recommend a good instance to me please?

**Comment by Pentaphon** [comment]
> Could you recommend a good instance to me please?

https://invidious.nerdvpn.de/watch?v=XL1iuROr8W4

**Comment by arkindal** [comment]
> > Could you recommend a good instance to me please?
> 
> https://invidious.nerdvpn.de/watch?v=XL1iuROr8W4

https://i.imgur.com/C3JZAl4.png

I guess this time it's on me.

**Comment by Pentaphon** [comment]
> I guess this time it's on me.

Not sure what is going on there. Maybe your location is the issue. I'm in the US. 

![Screenshot 2022-07-11 at 00-54-15 OnlyFans Is Nuts](https://user-images.githubusercontent.com/49374058/178215855-a58c13b7-9e80-4175-9956-ed18dac27f23.png)

**Comment by igorkulman** [comment]
Same issue. When I "log out" deleting cookies and local storage I cannot log back in, the login request never returns any response.

**Comment by Tha14** [comment]
> Same issue. When I "log out" deleting cookies and local storage I cannot log back in, the login request never returns any response.

Yes, the above has happened a few times in the past but the downtime was very short. This appears to be a extended, if not, permanent. The fact that the instance is missing from the preferences now is concerning.

What I don't like besides the lack of an update on the problem is that I recently subscribed to a few channels using the main instance and I decided to postpone exporting my subscriptions.

**Comment by mastazi** [comment]
I also could not see anything in the feed for more than a week, it used to be that there was a database error being returned (by looking at the networking tab in dev tools in the browser) but now I was getting some error about my session being stale, so I logged out by deleting cookies and session. 

When I went to log in... the login form told me I was using wrong username or password... which is impossible since I use a password manager.

So I went to "subscribe" page, entered my existing username, and boom -  I was able to create an account using my existing username -  meaning, my existing account had been deleted! 

I understand this is an open source project but having accounts deleted without warning  and without any comms from the devs is not something I'm OK with.

luckily a couple days before Piped started having issues, I had saved my list of subscriptions. So I am back to Invidious now, where I re-imported them. I'm sad because I really liked Piped better, for example I liked how on Piped the keyboard shortcuts worked well unlike Invidious where they don't work half of the time.

About a week ago when I first saw that Piped was having issues, I sent a donation to the devs to support them, I was hoping they could fix this but instead I ended up having my account wiped. Not happy.

**Comment by IceDBorn** [comment]
@mastazi If you're not happy with the official instance, selfhost one instead of complaining for the free services kavin is providing to you. I believe that your donation is most welcome, but it's nothing compared to the server cost for the official instance.

**Comment by arkindal** [comment]
> @mastazi If you're not happy with the official instance, selfhost one instead of complaining for the free services kavin is providing to you. I believe that your donation is most welcome, but it's nothing compared to the server cost for the official instance.

While I agree with part of your message, specifically saying we shouldn't complain for a free service, there's something you might've missed: quite a few users are experiencing that issue or extremely similar ones, and this is happening on multiple instances. I tried multiple instances myself.
And this issue has been going for a couple of weeks for multiple users, like me. I personally waited a bit because in the past I've had issues with piped that got solved in a day or two, so when things didn't work I wasn't all too concerned. But I've been unable to use it for a week or two now, so I started the thread. 

I'm typing all this to basically say: Suggesting to just use a different instance not only doesn't solve anything, but hints the fact that maybe not much of the thread has been read.

**Comment by IceDBorn** [comment]
@arkindal mah.fi works just fine though. I did not say that he shouldn't complain at all, but he's treating Piped as a product, by a company. He cannot say that he's not "happy" about a service provided by a single dev.

**Comment by arkindal** [comment]
> @arkindal mah.fi works just fine though. I did not say that he shouldn't complain at all, but he's treating Piped as a product, by a company. He cannot say that he's not "happy" about a service provided by a single dev.

And with that point I agree 100%

I'll test mah.fi and see if it works fine for me as well, are other instances giving you issues? Just to know if we're having similar issues on other instances, it might be good to figure out if the problem is with some specific instances or something else.

**Comment by hommegithub** [comment]
If we're still talking about piped, it won't even take up subscription .json with a new instance and account, it's to this point I open up an issue here.

https://github.com/TeamPiped/Piped/issues/1193

**Comment by mastazi** [comment]
@IceDBorn 95% of my comment is explaining the issue I had, the type of error messages I encountered, and the steps to follow to reproduce. I am introducing a new piece of information that no one in this thread reported before, specifically that there has been loss of accounts (since I could reopen with the same username) maybe the dev was not aware, now they are.

BUt instead you chose to focus on the remaining 5% of my comment where I complain, even though I started my complaint by saying

> I understand this is an open source project but ...

I'm familiar with OSS I contributed myself before so don't get all your panties in a pile.

**Comment by lima46zulu** [comment]
> @arkindal mah.fi works just fine though.

It doesn't work for me. My subscription/feed page is not showing anything even on that instance. Looks like the Feed issues impact multiple instances as others have pointed out.

**Comment by mastazi** [comment]
To those who can't see their feed, can you open an incognito window and attempt to log in? Are you still able to log in, or your account is gone like in my case that I explained [here](https://github.com/TeamPiped/Piped/issues/1195#issuecomment-1180298667)? I think this would be useful info for the devs.

**Comment by 0xJes** [comment]
I'm experiencing this problem too, my feed was empty for a while until I realized I was logged out, I tried to log in back, but it says wrong password/user, same error on my phone and a different browser.

My user and password is stored with KeePassXC.

I understand this is a free open source project, but I don't want to lose my subscription list, I don't remember them all.

**Comment by t5awd** [comment]
Yeah, I'm unable to check my feed on kavin.rocks, il.ax, or tohkmi.xyz.

**Comment by avo7** [comment]
I've been experiencing the same issue. Maybe this info will help:

JS console says:

```
FeedPage.vue:74 Uncaught (in promise) TypeError: this.videosStore.slice is not a function
    at Proxy.loadMoreVideos (FeedPage.vue:74:48)
    at FeedPage.vue:50:18
```

It looks like this is caused by an HTTP request to `https://pipedapi.kavin.rocks/feed?authToken=...` returning a 500 with the following body:

```
{"error":"jakarta.persistence.PersistenceException: Converting `org.hibernate.exception.GenericJDBCException` to JPA `PersistenceException` : JDBC exception executing SQL [select distinct v1_0.id,c1_0.uploader_id,c1_0.uploader,c1_0.uploader_avatar,c1_0.verified,v1_0.duration,v1_0.thumbnail,v1_0.title,v1_0.uploaded,v1_0.views from videos v1_0 join channels c1_0 on c1_0.uploader_id=v1_0.uploader_id,users u1_0 where v1_0.uploader_id in(select s1_0.channel from users_subscribed s1_0 where u1_0.id=s1_0.subscriber) and u1_0.id=? order by v1_0.uploaded desc]\n\tat org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)\n\tat org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:374)\n\tat org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:986)\n\tat me.kavin.piped.utils.ResponseHelper.feedResponse(ResponseHelper.java:881)\n\tat me.kavin.piped.ServerLauncher.lambda$mainServlet$28(ServerLauncher.java:257)\n\tat io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)\n\tat io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.hibernate.exception.GenericJDBCException: JDBC exception executing SQL [select distinct v1_0.id,c1_0.uploader_id,c1_0.uploader,c1_0.uploader_avatar,c1_0.verified,v1_0.duration,v1_0.thumbnail,v1_0.title,v1_0.uploaded,v1_0.views from videos v1_0 join channels c1_0 on c1_0.uploader_id=v1_0.uploader_id,users u1_0 where v1_0.uploader_id in(select s1_0.channel from users_subscribed s1_0 where u1_0.id=s1_0.subscriber) and u1_0.id=? order by v1_0.uploaded desc]\n\tat org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:61)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:253)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:146)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.lambda$processNext$0(JdbcValuesResultSetImpl.java:89)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advance(JdbcValuesResultSetImpl.java:274)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:85)\n\tat org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)\n\tat org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:89)\n\tat org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:142)\n\tat org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:32)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:437)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)\n\tat org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:102)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:305)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:246)\n\tat org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:536)\n\tat org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)\n\t... 8 more\nCaused by: org.postgresql.util.PSQLException: ERROR: query execution canceled\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)\n\tat com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)\n\tat com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:217)\n\t... 25 more\n","message":"Converting `org.hibernate.exception.GenericJDBCException` to JPA `PersistenceException` : JDBC exception executing SQL [select distinct v1_0.id,c1_0.uploader_id,c1_0.uploader,c1_0.uploader_avatar,c1_0.verified,v1_0.duration,v1_0.thumbnail,v1_0.title,v1_0.uploaded,v1_0.views from videos v1_0 join channels c1_0 on c1_0.uploader_id=v1_0.uploader_id,users u1_0 where v1_0.uploader_id in(select s1_0.channel from users_subscribed s1_0 where u1_0.id=s1_0.subscriber) and u1_0.id=? order by v1_0.uploaded desc]"}
````

**Comment by arkindal** [comment]
That's ok, do you guys reckon it's safe to make a new account now or should I wait after the 14?

**Comment by arkindal** [comment]
> > That's ok, do you guys reckon it's safe to make a new account now or should I wait after the 14?
> 
> I thought it wouldn't take my .json when I created an issue... I already opened a second account.

Is it working now for you?

**Comment by lbrdt** [comment]
> Hey. For those of you not in the Matrix room, here's what's going on according to Kavin:
> 
> ![kavinannouncement](https://user-images.githubusercontent.com/88680532/179043860-db9baca3-f847-4112-bdcd-12edf3af4f57.png)
> 
> Was just browsing Github and saw how confused you guys were, hopefully this clears some stuff up. If there are any significant updates on the Matrix I will let you all know. Have a great day!

Is there any discussion on why the feed isn't working on other instances as well?

**Comment by uuuussseer** [comment]
Hey. @lbrdt, other instances have been having trouble with importing, but nothing about other instance's feeds being down has been brought up to my knowledge. Kavin's instance has been down because of a cockroachdb error on his end. Maybe other instances tried to use cockroachdb and messed up their subscriptions too? Hosting errors? You may want to contact the instance you are using to see what's up. But **it's not an error with piped, it's an error with the instance**.

**Comment by uuuussseer** [comment]
Also, here's an announcement from Kavin:
![otherkavin](https://user-images.githubusercontent.com/88680532/179593410-783f6eca-5257-4225-b683-6bc2db338ba8.png)
Feeds should be coming/already online, so if you're on the official instance and have been having trouble with your feed, make sure to log back in and check your account.

I think that this should be a lesson for all of us to back-up our data frequently, and with a great open-source project as piped offering native exporting of your data, we should all be taking advantage of its exporting features. Have a great day everyone!

**Comment by RouterCFW** [comment]
Everything’s fixed now

**Comment by nonetrix** [comment]
Still having this issue only works like 5/10 times also thumbnails won't load sometimes

**Comment by jerlam06** [comment]
New to Piped, but it never worked on my W11 desktop. Works well on my mobile though. From the network tab the issue would seem to come from cloudflare, I get this: Access denied Error code 1020.
