### ISSUE TITLE
Login not responsive | Subscriptions and front page stop appearing

### ISSUE THREAD

**Issue by WolfShadowheart** [TeamPiped/Piped#2625]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Using Firefox

First arrival to the site - it all works as expected.

I created an account and subscribe to ~50 to 70 channels. 

Soon after while still logged in, my front page/feed is completely blank (only the Piped - Search - Pereferences ---> Feed appear). It will load for forever.

Clearing cookies will allow the site to load properly once more, however attempting to login leaves me with no responses - the page stays the same and no login occurs. 

This has been reproduced on piped.kavin.rocks and piped.video

### To Reproduce

1. creating an account with piped leads to an error that seems to be related to cookies
2. after creating an account and subscribing to channels, the site temporarily works.
3. after some time passes (closing browser *or* waiting a short period of time) trying to load into piped.video/feed or subscriptions leads the user to a blank page
4. attempting to login will have no response
5. at this stage, piped is effectively frozen. 
6. Clear cookies to be allow Piped.Video to be interacted with - videos appear and will play
7. However, the login issue remains.

### Expected behavior

Ideally the user creates an account, subscribes to the channels, and is able to logout and login at will.

### Browser, and OS with Version.

Firefox, Windows 10

### Additional context

1) Piped works when I do not login, and private browsing (i.e. no extensions) had the same results.
2)  When I first registered for an account, it soon failed, and I was unable to login again, I attempted to clear the cookies which loaded default videos. Login was still not available. 
3) The next day, nothing had changed (Piped was still broken/in this state). I tried to register for another account. 
4) I believe I used the same username.
5) As I resubscribed to channels that I had previously, Piped saves my categorized subscriptions, meaning "Music" or "Technology" channels I subscribed to and edited were still there from the initial setup. 

However, it again only worked for about 15 minutes before front page feed going blank, subscriptions being unviewable, and the login issues. 

My apologies for any inaccurate formatting or lack of details, and also for the odd set of reproducible steps. I'm unaware of how to get javascript logs, but would be happy to try and provide any - or any other information you may need. 

Thank you for this wonderful project, with this bug/issue solved I could see myself enjoying it very much.

**Comment by FireMasterK** [comment]
Hi there, this should be fixed!

**Comment by FlareHeart** [comment]
I still cannot sign in. I've cleared site data and reloaded on a fresh tab, still unable to sign back in.

**Comment by WolfShadowheart** [comment]
> 

Unfortunately I'm having the same issue as FlareHeart still, where trying to login is unresponsive. The trending page does load now after the issue though!

Thank you for your quick work on this!

**Comment by WolfShadowheart** [comment]
> Unfortunately I'm having the same issue as FlareHeart still, where trying to login is unresponsive. The trending page does load now after the issue though!


Just following up to say that I believe it is working as expected now - may have just needed some time for it to reflect on my end! Thank you very much!

@FlareHeart I seem to be able to login now on piped.video - are you still having issues?

**Comment by FlareHeart** [comment]
It is working for me now as well. Thanks for letting me know!
