### ISSUE TITLE
3004 error when play video

### ISSUE THREAD

**Issue by lost22git** [TeamPiped/Piped#3189]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

![Screenshot 2023-11-28 083855](https://github.com/TeamPiped/Piped/assets/65008815/b6c01dd2-4610-4ace-a44c-cb1e6c8a189a)

### To Reproduce

none

### Expected behavior

play video normally

### Browser, and OS with Version.

win11
brave 1.61.85

**Comment by FireMasterK** [comment]
Fixed in https://github.com/TeamPiped/Piped-Backend/pull/741.

**Comment by thisisjoesGH** [comment]
> Fixed in [TeamPiped/Piped-Backend#741](https://github.com/TeamPiped/Piped-Backend/pull/741).

Has the fix been pushed in the docker image? Still encountering this issue. I'm using docker compose if that's relevant.

**Comment by seonwoolee** [comment]
Same problem as thisisjoesGH, still seeing this problem in the Docker image. It's also annoying how there's literally only one tag for Docker images, latest, so I can't just go back to a previous image

**Comment by gbeliako** [comment]
still seeing the same problem in the docker image.
