### ISSUE TITLE
Some videos stop playing after 1 minute

### ISSUE THREAD

**Issue by shrugal** [TeamPiped/Piped#3689]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Video plays normally, and then stops with endless loading exactly at the one minute mark.

Example: https://piped.video/watch?v=W1ZZ-Yni8Fg (Edit: This video works now, but other still don't)

### To Reproduce

1. Play video
2. Wait 1 minute (or seek forward)
3. Video stops at 1:00

### Expected behavior

Video should keep playing.

### Logs/Errors

The videoplaypack requests to the proxy start returning 403 responses close to 1:00, so I guess that's got something to do with it:

![grafik](https://github.com/TeamPiped/Piped/assets/710525/df93db80-5933-4c78-9389-f85b241110d8)

No error message though. :/

### Browser, and OS with Version.

Firefox 127.0.2 on Windows 11.

**Comment by Atemu** [comment]
Since it's apparently a 403, I tried getting my server a new IPv6 address but that didn't help.

I can `curl` a yt video page and get a 200 back from the same server just fine too.

What's especially frustrating is that there is no error message here whatsoever. Just: Boom, 403; have fun figuring out anything.

**Comment by nvd916** [comment]
[SmartTube](https://github.com/yuliskov/SmartTube/issues) is having the same problem, so this must be something YouTube changed that affects alternative front-end applications.

**Comment by manuelkamp** [comment]
can confirm that I have that on some videos over the last week or two.

**Comment by Atemu** [comment]
This has been fixed in https://github.com/TeamPiped/Piped-Backend/commit/95a16effe503ae6f6ca11738c5ebfadbd703e0ac.

Update your piped-backend.

**Comment by manuelkamp** [comment]
ran watchtower update, `time="2024-07-11T11:22:36Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no`, so not fixed for me unfortunately

**Comment by Atemu** [comment]
Here are my image IDs for reference:

```
CONTAINER           REPOSITORY                 TAG                 IMAGE ID            SIZE
nginx               nginx                      mainline-alpine     099a2d701db1        43.2MB
piped-backend       1337kavin/piped            latest              2ab9a2493f8d        390MB
piped-frontend      1337kavin/piped-frontend   latest              0622243f6cd4        58.5MB
piped-proxy         1337kavin/piped-proxy      latest              4e83262534d3        92.4MB
postgres            postgres                   15                  e15c136afbfb        425MB
```

Are you sure you restarted the container with the new image?

**Comment by manuelkamp** [comment]
thank you
```REPOSITORY                 TAG               IMAGE ID       CREATED        SIZE
1337kavin/piped            latest            2ab9a2493f8d   17 hours ago   390MB
1337kavin/piped-proxy      latest            4e83262534d3   3 days ago     92.4MB
1337kavin/piped-frontend   latest            0622243f6cd4   8 days ago     58.5MB
nginx                      mainline-alpine   099a2d701db1   2 weeks ago    43.2MB
postgres                   15                e15c136afbfb   2 months ago   425MB
containrrr/watchtower      latest            e7dd50d07b86   8 months ago   14.7MB
```
yep, seems identical to me. the nightly watchtower job did fix the 1001 error for me, but not this one unfortunately. did manually restart the docker stack, same non-successful result

**Comment by Atemu** [comment]
I'd try the web frontend on some other device.

**Comment by leberschnitzel** [comment]
I have the same problem on my instance. The 1001 error and this one seem unrelated, since the 1001 is also fixed for me.
I notice the endless buffer after 59 seconds mostly on long videos and streams, like https://piped.video/watch?v=I8fU4T8BA64

**Comment by manuelkamp** [comment]
I have now a video, where it happens on TV and PC

```
Failed to load resource: the server responded with a status of 403 ()
viewtubeproxy.redacted.servername/videoplayback?bui=AXc671KtWmy3ABvTBFYnu0RQeiB4rI-Sbi69o2gDO_ii4cRSYSKa69euZ67PHrGMAMg4qjkdkE7JTfXk&c=WEB&clen=12980162&cpn=KCTgqXwAMyjAFRyF&dur=971.781&ei=g0yWZpm4KdKw6dsP8fqs4AI&expire=1721147619&fvip=5&gir=yes&host=rr1---sn-uigxx50n-8pxy.googlevideo.com&id=o-ALhGM1p-EUwH1eGpS9oODzLIfzNDBguymuSAUctBjEXT&initcwndbps=2863750&ip=5.44.210.143&itag=251&keepalive=yes&lmt=1721095635721560&lsig=AHlkHjAwRQIhAK1GzGGgu1fwNexhggTBob8seZxUONNNjNh2J8jE-L2_AiAoeRy53KcjN8BS0MhmRHiHc_vWbeDSUjroLvR5w0-weQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=-U&mime=audio%2Fwebm&mm=31%2C29&mn=sn-uigxx50n-8pxy%2Csn-4g5e6nsy&ms=au%2Crdu&mt=1721125534&mv=m&mvi=1&n=x4b8srnNtnvjHw&ns=3IHg-aAWOcYE6el2GW5TpuAQ&pl=21&requiressl=yes&rqh=1&sefc=1&sig=AJfQdSswRgIhAPkuxkDAnOEpw0OuVQM3FkiDfjAPt7UHVj4fRsyYfSlkAiEAjONoSZ6MRfH3lV3LgWlRTq0a9gzWxmjpKxVqZlWklaM%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&spc=NO7bAU-H6_66joFxYoZDCTVTpc5NuXie2IVh_kpaI8xDwswdyIhwkUHIvGYT&svpuc=1&txp=4432434&vprv=1&xpc=EgVo2aDSNQ%3D%3D&range=890746-1030944:1 
```

**Comment by shrugal** [comment]
I'm using the web frontend and LibreTube, and it only ever happend on the web with maybe 5% of the videos

Also, if I play an affected video to 1:00, then click the YT link for it, and then go back I often (not always) get the following error:

```js
{
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {},
    "The mediaSource_ status was closed expected 'open'",
    null
  ],
  "handled": false,
  "message": "Shaka Error 3015",
  "stack": "L@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:10:4472\nga/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:26112\n$o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:3740\npA/this.next@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4038\nt@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4267\npromise callback*o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4397\nfA/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4418\nfA@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4314\nM@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4452\nga@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:25452\np.init/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:25303\n$o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:3740\npA/this.next@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4038\nt@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4267\npromise callback*o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4397\nfA/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4418\nfA@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4314\nM@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4452\np.init@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:25095\nR2/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:66795\n$o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:3740\npA/this.next@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4038\nfA/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4421\nfA@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4314\nM@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4452\nR2@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:66555\np.start/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:63574\n$o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:3740\npA/this.next@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4038\nfA/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4421\nfA@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4314\nM@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4452\np.start@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:63539\nmx/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:133973\n$o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:3740\npA/this.next@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4038\nt@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4267\npromise callback*o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4397\nfA/<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4418\nfA@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4314\nM@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:4452\nmx@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:131771\np.load/</</<@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:15:124952\n$o@https://piped.server/assets/shaka-player.ui-BxG0Tsk8.js:6:3740\n"
}
```

To fix it I have to reload the page without cache, which makes it go back to endless buffering at 1:00 again.

**Comment by Bnyro** [comment]
Should be fixed with https://github.com/TeamPiped/Piped-Backend/commit/91751fd1fd9f9eb32386d872a69b7d7c3598b22a

**Comment by diagramduckdel** [comment]
I'm seeing this issue again -- I get a 403 from piped-proxy at approx. 1minute into a video. There's no logging in the proxy, so there's not much to figure out what might be going on, other than the HTTP code.

I noticed that it doesn't happen on all videos (no change in network cfg between them); I also noticed that a video that does display the issue may work when attempted later on (again, no change in network cfg).

Perhaps something related to countermeasures to prevent these players from working? (https://github.com/TeamPiped/Piped/issues/3658)

**Comment by seonwoolee** [comment]
I too am encountering this, with a 403 from piped-proxy at about 1 minute, like diagramduckdel. I haven't found anything in the logs that would given any indication as to why

**Comment by enticedwanderer** [comment]
Is it possible this has something to do with video encoding or CDN? In my experience, videos that encounter this problem work fine after a day or two. it sounds like YouTube didn't transcode the segments in time for the format being requested or they are not distributed through the CDN yet. Perhaps the backend expects the clients to fall back to a different format or location and piped doesn't?

But then I wonder why the first minute is there. Unless that part of transcoding is frontloadeded on YouTube side.

-------- Original Message --------

**Comment by shrugal** [comment]
This started happening again, about a week ago. This time with all videos, not just some of them:

![Image](https://github.com/user-attachments/assets/96e17a99-9331-4505-850a-a63e0dc7f915)
