### ISSUE TITLE
Subtitles Cover The Video(See Screenshot)

### ISSUE THREAD

**Issue by TanKot** [TeamPiped/Piped#805]
![image](https://user-images.githubusercontent.com/77598655/152918094-85b2039c-3d7b-4e3d-8b40-0898df5e15df.png)
This has been happening for a bit now.
It literally tints the video.
Is it just a glitch on my end?(If so please help fix it)
Or is it a backend issue?

**Comment by dhishkyaon** [comment]
happening for me too.

**Comment by Loki-L1130** [comment]
It is fixed few hours ago. See here : https://github.com/TeamPiped/Piped/issues/448

May be your Instance hasn't yet been updated if you are not using kavin.rocks

**Comment by dhishkyaon** [comment]
im using piped.kavin.rocks rn and its still happening
![Screenshot_20220208-140711.png](https://user-images.githubusercontent.com/88529066/152949216-a283ba6b-754c-4ca2-bccf-db25653c646f.png)

**Comment by TanKot** [comment]
Same here, its still not fixed.

**Comment by Loki-L1130** [comment]
I am piped.silkky.cloud Instance. It does not suffer from this issue.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/152974295-87c9ca2e-2c93-40eb-ac68-65e19b4361df.png)
It's fine on the official instance, you could try clearing the site data to remove any potentially outdated caches.

**Comment by dhishkyaon** [comment]
@FireMasterK yes its working. sorry for the trouble.
