### ISSUE TITLE
Backend - An error occoured in the path: /streams/myjEoDypUD8 org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException

### ISSUE THREAD

**Issue by IvRRimum** [TeamPiped/Piped#942]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

backend docker logs:
```
An error occoured in the path: /streams/myjEoDypUD8
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
        at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)
        at me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$1(ResponseHelper.java:113)
        at <unknown class>.get(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

frontend response:
```
{
"error": "org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)\n\tat me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$1(ResponseHelper.java:113)\n\tat <unknown class>.get(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)\n",
"message": "Could not get any stream. See error variable to get further details."
}
```

### To Reproduce

https://piped-api.crypto-tzar.com/streams/myjEoDypUD8

### Expected behavior

Should give stream

### Logs/Errors

Added in the main bug

### Browser, and OS with Version.

Doesnt matter

**Comment by kubo6472** [comment]
`org.schabi.newpipe.extractor.playlist.PlaylistInfoItem incompatible with org.schabi.newpipe.extractor.stream.StreamInfoItem` reproducable on official for me

**Comment by FireMasterK** [comment]
> `org.schabi.newpipe.extractor.playlist.PlaylistInfoItem incompatible with org.schabi.newpipe.extractor.stream.StreamInfoItem` reproducable on official for me

This was fixed in https://github.com/TeamPiped/Piped-Backend/pull/235 and is now deployed.

Additionally, the issue the author is facing has been fixed weeks ago and just needs a backend update, so I'm closing this issue.

**Comment by IvRRimum** [comment]
@FireMasterK I ran the backend update command provided in documentation:
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once piped-frontend piped-backend ytproxy varnish nginx caddy postgres watchtower
``` 

With no luck ://

**Comment by IvRRimum** [comment]
I just deleted my backends piped api
i redeployed the newest piped version
https://piped.crypto-tzar.com/watch?v=Ir2Q2WSQXwM[]
STILL doesnt work!

**Comment by IvRRimum** [comment]
Heres the error from backend:
```
An error occoured in the path: /streams/1N1RwMOcjks
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
        at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)
        at me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$1(ResponseHelper.java:113)
        at <unknown class>.get(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

**Comment by FireMasterK** [comment]
Your instance is still not up-to-date, I'd suggest running running:
```
docker-compose pull && docker-compose down && docker-compose up -d
```

An up-to-date instance should show it's version at https://piped-api.crypto-tzar.com/version
